theme: jekyll-theme-cayman
title: "sl"
description: "An utility tool to list npm scripts from package.json file"
show_downloads: "true"
github:
  zip_url: https://github.com/rousan/sl/zipball/master
  tar_url: https://github.com/rousan/sl/tarball/master